# Generated by Django 6.0.4 on 2026-04-13 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес установки')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('status', models.CharField(choices=[('ACTIVE', 'В работе'), ('BROKEN', 'Сломан'), ('MAINTENANCE', 'На обслуживании')], default='ACTIVE', max_length=20, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='MachineSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=10, verbose_name='Номер ячейки (A1, B2)')),
                ('current_quantity', models.PositiveIntegerField(default=0, verbose_name='Текущий остаток')),
                ('max_capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='vending.machine')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vending.product')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В работе'), ('DONE', 'Выполнена')], default='NEW', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vending.machine')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Техник')),
            ],
        ),
    ]
