# Generated by Django 6.0.4 on 2026-04-18 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='machineslot',
            name='slot_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Формат ячейки должен быть Буква+Цифра (например: A1, B12)', regex='^[A-Z]\\d{1,2}$')], verbose_name='Номер ячейки (A1, B2)'),
        ),
    ]
