# Generated by Django 6.0.6 on 2026-06-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0002_alter_machine_latitude_alter_machine_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetask',
            name='description',
            field=models.TextField(default='Неизвестная ошибка', verbose_name='Описание проблемы/Код ошибки'),
        ),
    ]
